# Generated by Django 3.2.9 on 2021-11-10 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_code', models.CharField(max_length=50)),
                ('pathogen', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Duser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=40)),
                ('salary', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MainTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('disease_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.disease')),
            ],
        ),
        migrations.CreateModel(
            name='PublicServant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('p_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.duser')),
            ],
        ),
        migrations.CreateModel(
            name='Specialize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.duser')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_deaths', models.IntegerField()),
                ('total_patients', models.IntegerField()),
                ('r_cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maintable')),
                ('r_disease_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disease')),
                ('r_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.publicservant')),
            ],
        ),
        migrations.AddField(
            model_name='duser',
            name='u_cname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maintable'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=20)),
                ('d_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.duser')),
            ],
        ),
        migrations.CreateModel(
            name='Discover',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_enc_date', models.DateField()),
                ('d_cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maintable')),
                ('d_disease_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disease')),
            ],
        ),
    ]
